IL-5220: Adds column freezing to data-grid.
InfoGroupInteractive/react-datagrid pull request #3
Opened 2016-10-04 17:24 UTC by vinayakpatil

2016-10-04 21:33 UTC, gregtalarico requested changes
does this generally rely on each column having a defined width?

2016-10-04 21:33 UTC, talarico43 commented on src/Header/index.jsx
> +        }
why do we need to remove the fixed columns only to add them right back?

2016-10-04 21:33 UTC, talarico43 commented on src/Row/index.jsx
> +        }
same as above

2016-10-04 21:33 UTC, talarico43 commented on src/Wrapper/index.jsx
> +        }
same

2016-10-04 21:33 UTC, talarico43 commented on src/index.jsx
> +            for (var i = props.fixedColumns.length; i < props.columns.length; i++){
do we need a check that the prop exists first?

2016-10-04 21:33 UTC, talarico43 commented on src/index.jsx
> +        for (var i = props.columns.length - 1; i >= props.fixedColumns.length; i--){
same do we need to check for the prop's existence first?

2016-10-04 21:33 UTC, talarico43 commented on src/index.jsx
> +                props.columns[props.startColIndex].sizeStyle = {
should we just be writing to width and minwidth instead of a new prop?

2016-10-04 21:33 UTC, talarico43 commented on src/Wrapper/index.jsx
> +                    cellWidth = cols[j].sizeStyle.width ? {width: cols[j].sizeStyle.width, minWidth: cols[j].sizeStyle.width}
do we need the extra sizeStyle object?

2016-10-04 21:33 UTC, talarico43 commented on src/index.jsx
> +        this.prepareFixedColumns(props, state);
should we check for the fixed props before doing preparing the fixed cols?

2016-10-04 21:33 UTC, talarico43 commented on src/index.jsx
> +                width = props.style.width - visibleColumnsWidth;
will visibleColumnsWidth ever be smaller that props.style.width

2016-10-05 06:42 UTC, vinayakpatil commented on src/index.jsx
> +            for (var i = props.fixedColumns.length; i < props.columns.length; i++){
It will have a default value of an empty array

2016-10-05 06:42 UTC, vinayakpatil commented on src/index.jsx
> +        for (var i = props.columns.length - 1; i >= props.fixedColumns.length; i--){
same

2016-10-05 08:23 UTC, vinayakpatil commented on src/Header/index.jsx
> +        }
This was added to support non-consecutive column freezing by moving them to the beginning. I have removed this now.

2016-10-05 08:24 UTC, vinayakpatil commented on src/Wrapper/index.jsx
> +                    cellWidth = cols[j].sizeStyle.width ? {width: cols[j].sizeStyle.width, minWidth: cols[j].sizeStyle.width}
sizeStyle is a built in prop used to assign inline styles to a column cell.

2016-10-05 08:25 UTC, vinayakpatil commented on src/index.jsx
> +                props.columns[props.startColIndex].sizeStyle = {
In order to avoid fluctuations, I am just changing inline styles of a column cell.

2016-10-05 08:26 UTC, vinayakpatil commented on src/index.jsx
> +        this.prepareFixedColumns(props, state);
I have moved this into prepareColumns function to save an extra cycle.

2016-10-05 08:28 UTC, vinayakpatil commented
I have added `minWidth` fallback in virtual column rendering logic now.

2016-10-06 11:21 UTC, vinayakpatil commented
@talarico43 Added suggested changes, can you please review?

2016-10-06 15:37 UTC, gregtalarico approved these changes

2016-10-07 14:26 UTC, merged