get final commits from Zippy; additions for pagination; remove crosstab jazz
InfoGroupInteractive/react-datagrid pull request #7
Opened 2017-06-28 20:24 UTC by talarico43

2017-06-29 07:58 UTC, vinayakpatil commented
:100:

2017-07-05 19:36 UTC, gnrlbzik requested changes

2017-07-05 19:36 UTC, gnrlbzik commented on dist/react-datagrid.js
> +	          console.log(newScrollPos);
you forgot console.log

2017-07-05 19:41 UTC, talarico43 commented on dist/react-datagrid.js
> +	          console.log(newScrollPos);
let me run the build. maybe we just havent built with that changes

2017-07-05 19:49 UTC, talarico43 commented on dist/react-datagrid.js
> +	          console.log(newScrollPos);
actually i think thats coming from the zippy updates.

2017-07-05 19:56 UTC, gnrlbzik approved these changes

2017-07-05 20:21 UTC, merged